### ISSUE TITLE
fedabipkgdiff reports display very few results

### ISSUE THREAD

**Issue by sergiomb2** [tkdchen/libabigail#1]
Hi, 
please let me know if I should report elsewhere but running [1] , reports display very few results [2] and I'm wondering if I'm not missing something . 

[1] 
fedabipkgdiff --all-subpackages opencv-4.3.0-9.fc33 opencv-4.5.0-4.fc34 --show-identical-binaries

[2]

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.aarch64.rpm and opencv-devel-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.aarch64.rpm and opencv-core-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.aarch64.rpm and opencv-java-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.aarch64.rpm and python3-opencv-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.aarch64.rpm and opencv-contrib-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.aarch64.rpm and opencv-4.5.0-4.fc34.aarch64.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.armv7hl.rpm and opencv-contrib-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.armv7hl.rpm and opencv-java-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.armv7hl.rpm and opencv-devel-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.armv7hl.rpm and opencv-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.armv7hl.rpm and python3-opencv-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.armv7hl.rpm and opencv-core-4.5.0-4.fc34.armv7hl.rpm:

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.i686.rpm and opencv-core-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.i686.rpm and opencv-contrib-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.i686.rpm and opencv-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.i686.rpm and python3-opencv-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.i686.rpm and opencv-devel-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.i686.rpm and opencv-java-4.5.0-4.fc34.i686.rpm:

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.ppc64le.rpm and opencv-core-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.ppc64le.rpm and opencv-contrib-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.ppc64le.rpm and opencv-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.ppc64le.rpm and python3-opencv-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.ppc64le.rpm and opencv-devel-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.ppc64le.rpm and opencv-java-4.5.0-4.fc34.ppc64le.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.s390x.rpm and python3-opencv-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.s390x.rpm and opencv-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.s390x.rpm and opencv-devel-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.s390x.rpm and opencv-core-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.s390x.rpm and opencv-contrib-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.s390x.rpm and opencv-java-4.5.0-4.fc34.s390x.rpm:

Comparing the ABI of binaries between python3-opencv-4.3.0-9.fc33.x86_64.rpm and python3-opencv-4.5.0-4.fc34.x86_64.rpm:

Comparing the ABI of binaries between opencv-contrib-4.3.0-9.fc33.x86_64.rpm and opencv-contrib-4.5.0-4.fc34.x86_64.rpm:

Comparing the ABI of binaries between opencv-java-4.3.0-9.fc33.x86_64.rpm and opencv-java-4.5.0-4.fc34.x86_64.rpm:

Comparing the ABI of binaries between opencv-4.3.0-9.fc33.x86_64.rpm and opencv-4.5.0-4.fc34.x86_64.rpm:

================ changes of 'opencv_interactive-calibration'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
  Function symbols changes summary: 0 Removed, 0 Added function symbol not referenced by debug info
  Variable symbols changes summary: 0 Removed, 1 Added variable symbol not referenced by debug info

  1 Added variable symbol not referenced by debug info:

    [A] __libc_single_threaded

================ end of changes of 'opencv_interactive-calibration'===============

================ changes of 'opencv_waldboost_detector'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
  Function symbols changes summary: 0 Removed, 0 Added function symbol not referenced by debug info
  Variable symbols changes summary: 0 Removed, 1 Added variable symbol not referenced by debug info

  1 Added variable symbol not referenced by debug info:

    [A] __libc_single_threaded

================ end of changes of 'opencv_waldboost_detector'===============

Comparing the ABI of binaries between opencv-core-4.3.0-9.fc33.x86_64.rpm and opencv-core-4.5.0-4.fc34.x86_64.rpm:

Comparing the ABI of binaries between opencv-devel-4.3.0-9.fc33.x86_64.rpm and opencv-devel-4.5.0-4.fc34.x86_64.rpm:

**Comment by sergiomb2** [comment]
one second example : 

/usr/bin/fedabipkgdiff --server https://koji.rpmfusion.org/kojihub --topurl https://koji.rpmfusion.org/kojifiles ffmpeg-4.2.4-3.fc32.x86_64 ffmpeg-4.3.1-16.fc33.x86_64 --show-identical-binaries --traceback

Comparing the ABI of binaries between ffmpeg-4.2.4-3.fc32.x86_64.rpm and ffmpeg-4.3.1-16.fc33.x86_64.rpm:

**Comment by tkdchen** [comment]
Hi @sergiomb2 

I think you could file this issue in http://sourceware.org/bugzilla/enter_bug.cgi?product=libabigail instead.

From https://www.sourceware.org/libabigail/ you can find more information about how to contact with the project maintainers.

This repository is not the official one and I haven't been working on libabigail for a quite long time.

Hope it is helpful.

**Comment by sergiomb2** [comment]
Than you

**Comment by tkdchen** [comment]
You are welcome.
